import os
import load_dotenv

load_dotenv.load_dotenv(".env")


OPENAI_API_KEY = os.getenv("ENV_OPENAI_API_KEY")
POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
DATABASE_URL = f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}/{POSTGRES_DB}"
ENVIRONMENT = os.getenv("ENVIRONMENT")
ALGORITHM = os.getenv("ENV_ALGORITHM")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ENV_ACCESS_TOKEN_EXPIRE_MINUTES"))
ACCESS_SECRET_KEY = os.getenv("ENV_ACCESS_SECRET_KEY")

BOT_CONTEXT_MESSAGE = """"""
